In [50]:
import pandas as pd
import numpy as np

In [9]:
df=pd.read_csv('/content/hotel_booking.csv')

In [2]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,Transient,0.0,0,0,Check-Out,2015-07-01,Ernest Barnes,Ernest.Barnes31@outlook.com,669-792-1661,************4322
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,Transient,0.0,0,0,Check-Out,2015-07-01,Andrea Baker,Andrea_Baker94@aol.com,858-637-6955,************9157
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,Transient,75.0,0,0,Check-Out,2015-07-02,Rebecca Parker,Rebecca_Parker@comcast.net,652-885-2745,************3734
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,Transient,75.0,0,0,Check-Out,2015-07-02,Laura Murray,Laura_M@gmail.com,364-656-8427,************5677
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,Transient,98.0,0,1,Check-Out,2015-07-03,Linda Hines,LHines@verizon.com,713-226-5883,************5498

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 36 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
 32  name                            119390 non-null  object
 33  email                           119390 non-null  object
 34  phone-number                    119390 non-null  object
 35  credit_card                     119390 non-null  object
dtypes: float64(4), int64(16), object(16)
memory usage: 32.8+ MB

In [14]:
df.drop(columns=[
    'name',
    'email',
    'phone-number',
    'credit_card'
], inplace=True)

In [12]:
clean_df=df.copy()

In [16]:
clean_df.drop(columns=[
    'name',
    'email',
    'phone-number',
    'credit_card'
], inplace=True)

In [17]:
clean_df.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

In [18]:
clean_df.columns=clean_df.columns.str.strip()
clean_df.columns=clean_df.columns.str.lower()
clean_df.columns=clean_df.columns.str.replace(" ", "_")

In [19]:
clean_df.duplicated().sum()

np.int64(31994)

In [20]:
clean_df.drop_duplicates(inplace=True)

In [26]:
clean_df["children"]=clean_df["children"].astype(int)

In [27]:
clean_df["agent"]=clean_df["agent"].fillna(0)

In [28]:
clean_df["agent"]=clean_df["agent"].astype(int)

In [29]:
clean_df["country"]=clean_df["country"].fillna("UnKnown")

In [30]:
clean_df["meal"]=clean_df["meal"].replace("Undefined", "UnKnown")

In [31]:
clean_df.drop(columns='company', inplace=True)

In [32]:
clean_df['reservation_status_date']=pd.to_datetime(clean_df['reservation_status_date'])

In [33]:
clean_df=clean_df[clean_df['children']<=6]

In [35]:
clean_df=clean_df[clean_df['babies']<=6]

In [36]:
clean_df=clean_df[clean_df['adr']>=0]

In [37]:
clean_df.isnull().sum()

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
agent                             0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
reservation_status_date           0
dtype: int64

In [38]:
clean_df['invalid_guest_count'] = ((clean_df['adults']==0) &
                             (clean_df['children']==0) &
                             (clean_df['babies']==0))

In [40]:
clean_df.to_csv('clean_hotel_booking.csv', index=False)

In [41]:
clean_df['total_guests'] = clean_df['adults'] + clean_df['children'] + clean_df['babies']

In [43]:
clean_df['total_stay_nights'] = clean_df['stays_in_weekend_nights'] + clean_df['stays_in_week_nights']

In [44]:
clean_df['booking_status'] = clean_df['is_canceled'].map({
    0:'Not Canceled',
    1:'Canceled'
})

In [45]:
clean_df['revenue'] = clean_df['adr'] * clean_df['total_stay_nights']

In [46]:
clean_df['year'] = clean_df['reservation_status_date'].dt.year
clean_df['month'] = clean_df['reservation_status_date'].dt.month_name()

In [47]:
clean_df['agent'] = clean_df['agent'].astype(str)

In [48]:
clean_df['lead_time_category'] = pd.cut(
    clean_df['lead_time'],
    bins=[-1,30,90,180,1000],
    labels=['Short','Medium','Long','Very Long']
)

In [49]:
clean_df['stay_category'] = pd.cut(
    clean_df['total_stay_nights'],
    bins=[0,3,7,100],
    labels=['Short Stay','Medium Stay','Long Stay']
)

In [51]:
clean_df['family_booking'] = np.where(
    (clean_df['children'] + clean_df['babies']) > 0,
    'Family',
    'No Family'
)

In [56]:
clean_df.to_csv('clean_hotel_booking.csv', index=False)